name: Build SBM Revamp
on:
  push:
    branches-ignore:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'maven'

      - name: sbm-support-rewrite (build + test)
        working-directory: ./sbm-support-rewrite :sbm-support-rewrite
        run: mvn --batch-mode clean package --projects

      - name: clean
        run: mvn clean

      - name: test-helper (build + test)
        run: mvn --batch-mode package --projects :test-helper

      - name: sbm-openrewrite (build + test)
        run: mvn --batch-mode package --projects :test-helper, :sbm-openrewrite

      - name: sbm-core (build)
        run: mvn -DskipTests --batch-mode package --projects :sbm-core

      - name: recipe-test-support (build)
        run: mvn -DskipTests --batch-mode package --projects :recipe-test-support

      - name: sbm-support-boot (build)
        run: mvn -DskipTests --batch-mode --projects :sbm-support-boot package

      - name: sbm-support-jee (build)
        run: mvn -DskipTests --batch-mode --projects :sbm-support-jee

      - name: sbm-support-weblogic (build)
        run: mvn -DskipTests --batch-mode --projects :sbm-support-weblogic

      - name: sbm-recipes-jee-to-boot (build)
        run: mvn -DskipTests --batch-mode --projects :sbm-recipes-jee-to-boot

      - name: sbm-recipes-spring-cloud (build)
        run: mvn -DskipTests --batch-mode --projects :sbm-recipes-spring-cloud

      - name: sbm-recipes-boot-upgrade (build)
        run: mvn -DskipTests --batch-mode --projects :sbm-recipes-boot-upgrade