name: Build
on:
  push:
    branches:
      - "**"
    paths:
      - "sbm-support-rewrite/**"
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sbm-support-rewrite
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'maven'

      - name: Maven Build
        run: mvn --batch-mode clean package

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        with:
          version: 2.46.2
        env:
          JF_ARTIFACTORY_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}
      - name: Deploy to Artifactory
        run: |
          jfrog mvnc \
            --server-id-deploy spring-snapshot \
            --server-url https.//repo.spring.io \
            --repo-deploy-releases release \
            --repo-deploy-snapshots snapshot
          echo JFROG_CLI_BUILD_NAME=sbm-support-rewrite >> $GITHUB_ENV
          echo JFROG_CLI_BUILD_NUMBER=$GITHUB_RUN_NUMBER >> $GITHUB_ENV
      - name: Build and Publish
        env:
          DISABLE_SAMPLES: true
        run: |
          jfrog mvn clean install -B -Pci -DskipTests 
          jfrog build-publish
